# Generated by Django 5.0.6 on 2024-05-31 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="name",
            new_name="tag",
        ),
    ]
