# Generated by Django 5.0.6 on 2024-06-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0002_rename_name_tag_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="description",
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name="quote",
            name="quote",
            field=models.TextField(max_length=1350),
        ),
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(max_length=25),
        ),
    ]
