# Generated by Django 5.0.6 on 2024-06-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0007_alter_author_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="description",
            field=models.CharField(unique=True),
        ),
    ]
