# Generated by Django 5.0.6 on 2024-06-02 12:29

import quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0009_alter_author_description"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="author",
            index=models.Index(
                quotes.models.MD5("description"), name="author_description_idx"
            ),
        ),
    ]
