# Generated by Django 5.0.6 on 2024-06-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0011_alter_author_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(max_length=50),
        ),
    ]
